// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createEmailDispatch = `-- name: CreateEmailDispatch :one
INSERT INTO email_dispatches(
  email_request_id,
  resend_email_id,
  resend_payload,
  status,
  http_status_code,
  resend_error
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email_request_id, resend_email_id, resend_payload, status, http_status_code, resend_error, dispatched_at
`

type CreateEmailDispatchParams struct {
	EmailRequestID uuid.UUID       `json:"email_request_id"`
	ResendEmailID  *string         `json:"resend_email_id"`
	ResendPayload  json.RawMessage `json:"resend_payload"`
	Status         string          `json:"status"`
	HttpStatusCode *int32          `json:"http_status_code"`
	ResendError    *string         `json:"resend_error"`
}

// Records an email dispatch to the email sending service for compliance
// purposes
func (q *Queries) CreateEmailDispatch(ctx context.Context, arg CreateEmailDispatchParams) (EmailDispatch, error) {
	row := q.db.QueryRow(ctx, createEmailDispatch,
		arg.EmailRequestID,
		arg.ResendEmailID,
		arg.ResendPayload,
		arg.Status,
		arg.HttpStatusCode,
		arg.ResendError,
	)
	var i EmailDispatch
	err := row.Scan(
		&i.ID,
		&i.EmailRequestID,
		&i.ResendEmailID,
		&i.ResendPayload,
		&i.Status,
		&i.HttpStatusCode,
		&i.ResendError,
		&i.DispatchedAt,
	)
	return i, err
}

const getEmailRequestByID = `-- name: GetEmailRequestByID :one
select id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at
from email_requests
where id = $1
limit 1
`

func (q *Queries) GetEmailRequestByID(ctx context.Context, id uuid.UUID) (EmailRequest, error) {
	row := q.db.QueryRow(ctx, getEmailRequestByID, id)
	var i EmailRequest
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.QueueMessageID,
		&i.Exchange,
		&i.RoutingKey,
		&i.FromAddress,
		&i.ReplyTo,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Attachments,
		&i.TemplateID,
		&i.TemplateVars,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getEmailRequestByQueueMessageID = `-- name: GetEmailRequestByQueueMessageID :one
select id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at
from email_requests
where queue_message_id = $1
limit 1
`

// Used to detect a duplicate send before calling Resend: if a request with
// this queue_message_id was already dispatched, the caller must skip
// resending rather than upsert-and-retry, or a legitimate DLX redelivery
// and an external duplicate republish become indistinguishable and both
// would trigger a second real send.
func (q *Queries) GetEmailRequestByQueueMessageID(ctx context.Context, queueMessageID string) (EmailRequest, error) {
	row := q.db.QueryRow(ctx, getEmailRequestByQueueMessageID, queueMessageID)
	var i EmailRequest
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.QueueMessageID,
		&i.Exchange,
		&i.RoutingKey,
		&i.FromAddress,
		&i.ReplyTo,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Attachments,
		&i.TemplateID,
		&i.TemplateVars,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getEmailRequestByService = `-- name: GetEmailRequestByService :many
select id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at
from email_requests
where service_id = $1
order by received_at desc
limit $2 offset $3
`

type GetEmailRequestByServiceParams struct {
	ServiceID string `json:"service_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

// Orders the time it was recieved ie the most previous
func (q *Queries) GetEmailRequestByService(ctx context.Context, arg GetEmailRequestByServiceParams) ([]EmailRequest, error) {
	rows, err := q.db.Query(ctx, getEmailRequestByService, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailRequest{}
	for rows.Next() {
		var i EmailRequest
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.QueueMessageID,
			&i.Exchange,
			&i.RoutingKey,
			&i.FromAddress,
			&i.ReplyTo,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.Attachments,
			&i.TemplateID,
			&i.TemplateVars,
			&i.Status,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailRequestStatusByID = `-- name: UpdateEmailRequestStatusByID :one
UPDATE email_requests
  SET status = $2
  WHERE id = $1
RETURNING id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at
`

type UpdateEmailRequestStatusByIDParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Updates an email_request record effectively setting its status to one of
// the predefined statuses
func (q *Queries) UpdateEmailRequestStatusByID(ctx context.Context, arg UpdateEmailRequestStatusByIDParams) (EmailRequest, error) {
	row := q.db.QueryRow(ctx, updateEmailRequestStatusByID, arg.ID, arg.Status)
	var i EmailRequest
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.QueueMessageID,
		&i.Exchange,
		&i.RoutingKey,
		&i.FromAddress,
		&i.ReplyTo,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Attachments,
		&i.TemplateID,
		&i.TemplateVars,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const upsertEmailRequest = `-- name: UpsertEmailRequest :one
INSERT INTO email_requests (
  service_id,
  queue_message_id,
  exchange,
  routing_key,

  from_address,
  reply_to,
  to_addresses,
  cc_addresses,
  bcc_addresses,
  subject,
  body_html,
  body_text,
  attachments,

  template_id,
  template_vars,

  status,
  processed_at

) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (queue_message_id) DO UPDATE SET
  status = EXCLUDED.status,
  processed_at = EXCLUDED.processed_at
RETURNING id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at
`

type UpsertEmailRequestParams struct {
	ServiceID      string          `json:"service_id"`
	QueueMessageID string          `json:"queue_message_id"`
	Exchange       string          `json:"exchange"`
	RoutingKey     string          `json:"routing_key"`
	FromAddress    string          `json:"from_address"`
	ReplyTo        *string         `json:"reply_to"`
	ToAddresses    []string        `json:"to_addresses"`
	CcAddresses    []string        `json:"cc_addresses"`
	BccAddresses   []string        `json:"bcc_addresses"`
	Subject        string          `json:"subject"`
	BodyHtml       *string         `json:"body_html"`
	BodyText       *string         `json:"body_text"`
	Attachments    json.RawMessage `json:"attachments"`
	TemplateID     *string         `json:"template_id"`
	TemplateVars   json.RawMessage `json:"template_vars"`
	Status         string          `json:"status"`
	ProcessedAt    *time.Time      `json:"processed_at"`
}

// Persists an email request to the database for replayability, or updates
// it in place if this is a retry of the same queue_message_id (dead-lettered
// redelivery) — retrying must not hit the queue_message_id UNIQUE
// constraint as a fresh insert, or the retry mechanism would just fail
// forever on the second attempt without ever reaching Resend again.
func (q *Queries) UpsertEmailRequest(ctx context.Context, arg UpsertEmailRequestParams) (EmailRequest, error) {
	row := q.db.QueryRow(ctx, upsertEmailRequest,
		arg.ServiceID,
		arg.QueueMessageID,
		arg.Exchange,
		arg.RoutingKey,
		arg.FromAddress,
		arg.ReplyTo,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.Attachments,
		arg.TemplateID,
		arg.TemplateVars,
		arg.Status,
		arg.ProcessedAt,
	)
	var i EmailRequest
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.QueueMessageID,
		&i.Exchange,
		&i.RoutingKey,
		&i.FromAddress,
		&i.ReplyTo,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Attachments,
		&i.TemplateID,
		&i.TemplateVars,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}
