// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_recipients.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEmailRecipient = `-- name: CreateEmailRecipient :one
INSERT INTO email_recipients (
  email_id, recipient_id, recieve_type
) VALUES ( $1, $2, $3)
RETURNING id, email_id, recipient_id, recieve_type, created_at, updated_at
`

type CreateEmailRecipientParams struct {
	EmailID     uuid.UUID     `json:"email_id"`
	RecipientID uuid.UUID     `json:"recipient_id"`
	RecieveType RecipientType `json:"recieve_type"`
}

func (q *Queries) CreateEmailRecipient(ctx context.Context, arg CreateEmailRecipientParams) (EmailRecipient, error) {
	row := q.db.QueryRow(ctx, createEmailRecipient, arg.EmailID, arg.RecipientID, arg.RecieveType)
	var i EmailRecipient
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.RecipientID,
		&i.RecieveType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailRecipients = `-- name: GetEmailRecipients :many
SELECT id, email_id, recipient_id, recieve_type, created_at, updated_at
FROM email_recipients WHERE email_id = $1
ORDER BY created_at ASC
LIMIT $2
OFFSET $3
`

type GetEmailRecipientsParams struct {
	EmailID uuid.UUID `json:"email_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetEmailRecipients(ctx context.Context, arg GetEmailRecipientsParams) ([]EmailRecipient, error) {
	rows, err := q.db.Query(ctx, getEmailRecipients, arg.EmailID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailRecipient{}
	for rows.Next() {
		var i EmailRecipient
		if err := rows.Scan(
			&i.ID,
			&i.EmailID,
			&i.RecipientID,
			&i.RecieveType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
