// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emails.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createEmailDispatch = `-- name: CreateEmailDispatch :one
INSERT INTO email_dispatches(
  email_request_id,
  resend_email_id,
  resend_payload,
  status,
  http_status_code,
  resend_error
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email_request_id, resend_email_id, resend_payload, status, http_status_code, resend_error, dispatched_at
`

type CreateEmailDispatchParams struct {
	EmailRequestID uuid.UUID       `json:"email_request_id"`
	ResendEmailID  *string         `json:"resend_email_id"`
	ResendPayload  json.RawMessage `json:"resend_payload"`
	Status         string          `json:"status"`
	HttpStatusCode *int32          `json:"http_status_code"`
	ResendError    *string         `json:"resend_error"`
}

// Records an email dispatch to the email sending service for compliance
// purposes
func (q *Queries) CreateEmailDispatch(ctx context.Context, arg CreateEmailDispatchParams) (EmailDispatch, error) {
	row := q.db.QueryRow(ctx, createEmailDispatch,
		arg.EmailRequestID,
		arg.ResendEmailID,
		arg.ResendPayload,
		arg.Status,
		arg.HttpStatusCode,
		arg.ResendError,
	)
	var i EmailDispatch
	err := row.Scan(
		&i.ID,
		&i.EmailRequestID,
		&i.ResendEmailID,
		&i.ResendPayload,
		&i.Status,
		&i.HttpStatusCode,
		&i.ResendError,
		&i.DispatchedAt,
	)
	return i, err
}

const createEmailRequest = `-- name: CreateEmailRequest :one
INSERT INTO email_requests (
  service_id, 
  queue_message_id,
  exchange,
  routing_key,

  from_address,
  reply_to,
  to_addresses,
  cc_addresses,
  bcc_addresses,
  subject,
  body_html,
  body_text,
  attachments,

  template_id,
  template_vars,

  status,
  processed_at

) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at
`

type CreateEmailRequestParams struct {
	ServiceID      string          `json:"service_id"`
	QueueMessageID string          `json:"queue_message_id"`
	Exchange       string          `json:"exchange"`
	RoutingKey     string          `json:"routing_key"`
	FromAddress    string          `json:"from_address"`
	ReplyTo        *string         `json:"reply_to"`
	ToAddresses    []string        `json:"to_addresses"`
	CcAddresses    []string        `json:"cc_addresses"`
	BccAddresses   []string        `json:"bcc_addresses"`
	Subject        string          `json:"subject"`
	BodyHtml       *string         `json:"body_html"`
	BodyText       *string         `json:"body_text"`
	Attachments    json.RawMessage `json:"attachments"`
	TemplateID     *string         `json:"template_id"`
	TemplateVars   json.RawMessage `json:"template_vars"`
	Status         string          `json:"status"`
	ProcessedAt    *time.Time      `json:"processed_at"`
}

// Persists an email request to the database for replayability
func (q *Queries) CreateEmailRequest(ctx context.Context, arg CreateEmailRequestParams) (EmailRequest, error) {
	row := q.db.QueryRow(ctx, createEmailRequest,
		arg.ServiceID,
		arg.QueueMessageID,
		arg.Exchange,
		arg.RoutingKey,
		arg.FromAddress,
		arg.ReplyTo,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.Attachments,
		arg.TemplateID,
		arg.TemplateVars,
		arg.Status,
		arg.ProcessedAt,
	)
	var i EmailRequest
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.QueueMessageID,
		&i.Exchange,
		&i.RoutingKey,
		&i.FromAddress,
		&i.ReplyTo,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Attachments,
		&i.TemplateID,
		&i.TemplateVars,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getEmailRequestByID = `-- name: GetEmailRequestByID :one
SELECT id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at FROM email_requests WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailRequestByID(ctx context.Context, id uuid.UUID) (EmailRequest, error) {
	row := q.db.QueryRow(ctx, getEmailRequestByID, id)
	var i EmailRequest
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.QueueMessageID,
		&i.Exchange,
		&i.RoutingKey,
		&i.FromAddress,
		&i.ReplyTo,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Attachments,
		&i.TemplateID,
		&i.TemplateVars,
		&i.Status,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getEmailRequestByService = `-- name: GetEmailRequestByService :many
SELECT id, service_id, queue_message_id, exchange, routing_key, from_address, reply_to, to_addresses, cc_addresses, bcc_addresses, subject, body_html, body_text, attachments, template_id, template_vars, status, received_at, processed_at FROM email_requests WHERE service_id = $1 ORDER BY received_at DESC
`

// Orders the time it was recieved ie the most previous
func (q *Queries) GetEmailRequestByService(ctx context.Context, serviceID string) ([]EmailRequest, error) {
	rows, err := q.db.Query(ctx, getEmailRequestByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailRequest{}
	for rows.Next() {
		var i EmailRequest
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.QueueMessageID,
			&i.Exchange,
			&i.RoutingKey,
			&i.FromAddress,
			&i.ReplyTo,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.Attachments,
			&i.TemplateID,
			&i.TemplateVars,
			&i.Status,
			&i.ReceivedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
