// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (
  external_id,
  subject,
  body,
  reply_to,
  source_service_id,
  source_user_id,
  source_user_email,
  schedule_for,
  delivery_status
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, external_id, subject, body, reply_to, source_service_id, source_user_id, source_user_email, schedule_for, delivered_at, delivery_status, created_at, updated_at
`

type CreateEmailParams struct {
	ExternalID      pgtype.UUID      `json:"external_id"`
	Subject         *string          `json:"subject"`
	Body            *string          `json:"body"`
	ReplyTo         *string          `json:"reply_to"`
	SourceServiceID *string          `json:"source_service_id"`
	SourceUserID    pgtype.UUID      `json:"source_user_id"`
	SourceUserEmail *string          `json:"source_user_email"`
	ScheduleFor     pgtype.Timestamp `json:"schedule_for"`
	DeliveryStatus  SentStatus       `json:"delivery_status"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.ExternalID,
		arg.Subject,
		arg.Body,
		arg.ReplyTo,
		arg.SourceServiceID,
		arg.SourceUserID,
		arg.SourceUserEmail,
		arg.ScheduleFor,
		arg.DeliveryStatus,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Subject,
		&i.Body,
		&i.ReplyTo,
		&i.SourceServiceID,
		&i.SourceUserID,
		&i.SourceUserEmail,
		&i.ScheduleFor,
		&i.DeliveredAt,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByExternalID = `-- name: GetEmailByExternalID :one
SELECT id, external_id, subject, body, reply_to, source_service_id,
source_user_id, source_user_email, schedule_for, delivered_at, delivery_status,
created_at, updated_at
FROM emails WHERE external_id=$1 LIMIT 1
`

func (q *Queries) GetEmailByExternalID(ctx context.Context, externalID pgtype.UUID) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByExternalID, externalID)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Subject,
		&i.Body,
		&i.ReplyTo,
		&i.SourceServiceID,
		&i.SourceUserID,
		&i.SourceUserEmail,
		&i.ScheduleFor,
		&i.DeliveredAt,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, external_id, subject, body, reply_to, source_service_id,
source_user_id, source_user_email, schedule_for, delivered_at, delivery_status,
created_at, updated_at
FROM emails WHERE id=$1 LIMIT 1
`

func (q *Queries) GetEmailByID(ctx context.Context, id uuid.UUID) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByID, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Subject,
		&i.Body,
		&i.ReplyTo,
		&i.SourceServiceID,
		&i.SourceUserID,
		&i.SourceUserEmail,
		&i.ScheduleFor,
		&i.DeliveredAt,
		&i.DeliveryStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
