// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldNotifications = `-- name: CleanupOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '90 days'
  AND status IN ('delivered', 'failed')
`

func (q *Queries) CleanupOldNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldNotifications)
	return err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    app_id,
    included_segments,
    excluded_segments,
    include_player_ids,
    include_external_user_ids,
    include_email_tokens,
    include_phone_numbers,
    include_ios_tokens,
    include_wp_wns_uris,
    include_amazon_reg_ids,
    include_chrome_reg_ids,
    include_chrome_web_reg_ids,
    include_android_reg_ids,
    contents,
    headings,
    subtitle,
    big_picture,
    large_icon,
    small_icon,
    ios_attachments,
    android_channel_id,
    android_accent_color,
    android_led_color,
    android_group,
    android_group_message,
    android_sound,
    ios_sound,
    wp_wns_sound,
    adm_sound,
    chrome_web_image,
    chrome_web_icon,
    chrome_web_badge,
    chrome_web_color,
    chrome_web_sound,
    url,
    web_url,
    app_url,
    data,
    filters,
    tags,
    send_after,
    delayed_option,
    delivery_time_of_day,
    ttl,
    priority,
    target_user_id,
    source_service_id,
    source_user_id,
    notification_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39,
    $40, $41, $42, $43, $44, $45, $46, $47, $48, $49
)
RETURNING id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at
`

type CreateNotificationParams struct {
	AppID                  string           `json:"app_id"`
	IncludedSegments       []string         `json:"included_segments"`
	ExcludedSegments       []string         `json:"excluded_segments"`
	IncludePlayerIds       []string         `json:"include_player_ids"`
	IncludeExternalUserIds []string         `json:"include_external_user_ids"`
	IncludeEmailTokens     []string         `json:"include_email_tokens"`
	IncludePhoneNumbers    []string         `json:"include_phone_numbers"`
	IncludeIosTokens       []string         `json:"include_ios_tokens"`
	IncludeWpWnsUris       []string         `json:"include_wp_wns_uris"`
	IncludeAmazonRegIds    []string         `json:"include_amazon_reg_ids"`
	IncludeChromeRegIds    []string         `json:"include_chrome_reg_ids"`
	IncludeChromeWebRegIds []string         `json:"include_chrome_web_reg_ids"`
	IncludeAndroidRegIds   []string         `json:"include_android_reg_ids"`
	Contents               json.RawMessage  `json:"contents"`
	Headings               json.RawMessage  `json:"headings"`
	Subtitle               json.RawMessage  `json:"subtitle"`
	BigPicture             *string          `json:"big_picture"`
	LargeIcon              *string          `json:"large_icon"`
	SmallIcon              *string          `json:"small_icon"`
	IosAttachments         json.RawMessage  `json:"ios_attachments"`
	AndroidChannelID       *string          `json:"android_channel_id"`
	AndroidAccentColor     *string          `json:"android_accent_color"`
	AndroidLedColor        *string          `json:"android_led_color"`
	AndroidGroup           *string          `json:"android_group"`
	AndroidGroupMessage    json.RawMessage  `json:"android_group_message"`
	AndroidSound           *string          `json:"android_sound"`
	IosSound               *string          `json:"ios_sound"`
	WpWnsSound             *string          `json:"wp_wns_sound"`
	AdmSound               *string          `json:"adm_sound"`
	ChromeWebImage         *string          `json:"chrome_web_image"`
	ChromeWebIcon          *string          `json:"chrome_web_icon"`
	ChromeWebBadge         *string          `json:"chrome_web_badge"`
	ChromeWebColor         *string          `json:"chrome_web_color"`
	ChromeWebSound         *string          `json:"chrome_web_sound"`
	Url                    *string          `json:"url"`
	WebUrl                 *string          `json:"web_url"`
	AppUrl                 *string          `json:"app_url"`
	Data                   json.RawMessage  `json:"data"`
	Filters                json.RawMessage  `json:"filters"`
	Tags                   json.RawMessage  `json:"tags"`
	SendAfter              pgtype.Timestamp `json:"send_after"`
	DelayedOption          *string          `json:"delayed_option"`
	DeliveryTimeOfDay      pgtype.Time      `json:"delivery_time_of_day"`
	Ttl                    *int32           `json:"ttl"`
	Priority               *int32           `json:"priority"`
	TargetUserID           pgtype.UUID      `json:"target_user_id"`
	SourceServiceID        *string          `json:"source_service_id"`
	SourceUserID           pgtype.UUID      `json:"source_user_id"`
	NotificationType       *string          `json:"notification_type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.AppID,
		arg.IncludedSegments,
		arg.ExcludedSegments,
		arg.IncludePlayerIds,
		arg.IncludeExternalUserIds,
		arg.IncludeEmailTokens,
		arg.IncludePhoneNumbers,
		arg.IncludeIosTokens,
		arg.IncludeWpWnsUris,
		arg.IncludeAmazonRegIds,
		arg.IncludeChromeRegIds,
		arg.IncludeChromeWebRegIds,
		arg.IncludeAndroidRegIds,
		arg.Contents,
		arg.Headings,
		arg.Subtitle,
		arg.BigPicture,
		arg.LargeIcon,
		arg.SmallIcon,
		arg.IosAttachments,
		arg.AndroidChannelID,
		arg.AndroidAccentColor,
		arg.AndroidLedColor,
		arg.AndroidGroup,
		arg.AndroidGroupMessage,
		arg.AndroidSound,
		arg.IosSound,
		arg.WpWnsSound,
		arg.AdmSound,
		arg.ChromeWebImage,
		arg.ChromeWebIcon,
		arg.ChromeWebBadge,
		arg.ChromeWebColor,
		arg.ChromeWebSound,
		arg.Url,
		arg.WebUrl,
		arg.AppUrl,
		arg.Data,
		arg.Filters,
		arg.Tags,
		arg.SendAfter,
		arg.DelayedOption,
		arg.DeliveryTimeOfDay,
		arg.Ttl,
		arg.Priority,
		arg.TargetUserID,
		arg.SourceServiceID,
		arg.SourceUserID,
		arg.NotificationType,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.IncludedSegments,
		&i.ExcludedSegments,
		&i.IncludePlayerIds,
		&i.IncludeExternalUserIds,
		&i.IncludeEmailTokens,
		&i.IncludePhoneNumbers,
		&i.IncludeIosTokens,
		&i.IncludeWpWnsUris,
		&i.IncludeAmazonRegIds,
		&i.IncludeChromeRegIds,
		&i.IncludeChromeWebRegIds,
		&i.IncludeAndroidRegIds,
		&i.Contents,
		&i.Headings,
		&i.Subtitle,
		&i.Buttons,
		&i.WebButtons,
		&i.BigPicture,
		&i.LargeIcon,
		&i.SmallIcon,
		&i.IosAttachments,
		&i.AndroidChannelID,
		&i.AndroidAccentColor,
		&i.AndroidLedColor,
		&i.AndroidGroup,
		&i.AndroidGroupMessage,
		&i.AndroidSound,
		&i.IosSound,
		&i.WpWnsSound,
		&i.AdmSound,
		&i.ChromeWebImage,
		&i.ChromeWebIcon,
		&i.ChromeWebBadge,
		&i.ChromeWebColor,
		&i.ChromeWebSound,
		&i.Url,
		&i.WebUrl,
		&i.AppUrl,
		&i.Data,
		&i.Filters,
		&i.Tags,
		&i.SendAfter,
		&i.DelayedOption,
		&i.DeliveryTimeOfDay,
		&i.Ttl,
		&i.Priority,
		&i.OnesignalNotificationID,
		&i.OnesignalStatus,
		&i.OnesignalResponse,
		&i.OnesignalError,
		&i.TargetUserID,
		&i.SourceServiceID,
		&i.SourceUserID,
		&i.NotificationType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DeliveredAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotification, id)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.IncludedSegments,
		&i.ExcludedSegments,
		&i.IncludePlayerIds,
		&i.IncludeExternalUserIds,
		&i.IncludeEmailTokens,
		&i.IncludePhoneNumbers,
		&i.IncludeIosTokens,
		&i.IncludeWpWnsUris,
		&i.IncludeAmazonRegIds,
		&i.IncludeChromeRegIds,
		&i.IncludeChromeWebRegIds,
		&i.IncludeAndroidRegIds,
		&i.Contents,
		&i.Headings,
		&i.Subtitle,
		&i.Buttons,
		&i.WebButtons,
		&i.BigPicture,
		&i.LargeIcon,
		&i.SmallIcon,
		&i.IosAttachments,
		&i.AndroidChannelID,
		&i.AndroidAccentColor,
		&i.AndroidLedColor,
		&i.AndroidGroup,
		&i.AndroidGroupMessage,
		&i.AndroidSound,
		&i.IosSound,
		&i.WpWnsSound,
		&i.AdmSound,
		&i.ChromeWebImage,
		&i.ChromeWebIcon,
		&i.ChromeWebBadge,
		&i.ChromeWebColor,
		&i.ChromeWebSound,
		&i.Url,
		&i.WebUrl,
		&i.AppUrl,
		&i.Data,
		&i.Filters,
		&i.Tags,
		&i.SendAfter,
		&i.DelayedOption,
		&i.DeliveryTimeOfDay,
		&i.Ttl,
		&i.Priority,
		&i.OnesignalNotificationID,
		&i.OnesignalStatus,
		&i.OnesignalResponse,
		&i.OnesignalError,
		&i.TargetUserID,
		&i.SourceServiceID,
		&i.SourceUserID,
		&i.NotificationType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getNotificationByOneSignalID = `-- name: GetNotificationByOneSignalID :one
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE onesignal_notification_id = $1
`

func (q *Queries) GetNotificationByOneSignalID(ctx context.Context, onesignalNotificationID *string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByOneSignalID, onesignalNotificationID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.IncludedSegments,
		&i.ExcludedSegments,
		&i.IncludePlayerIds,
		&i.IncludeExternalUserIds,
		&i.IncludeEmailTokens,
		&i.IncludePhoneNumbers,
		&i.IncludeIosTokens,
		&i.IncludeWpWnsUris,
		&i.IncludeAmazonRegIds,
		&i.IncludeChromeRegIds,
		&i.IncludeChromeWebRegIds,
		&i.IncludeAndroidRegIds,
		&i.Contents,
		&i.Headings,
		&i.Subtitle,
		&i.Buttons,
		&i.WebButtons,
		&i.BigPicture,
		&i.LargeIcon,
		&i.SmallIcon,
		&i.IosAttachments,
		&i.AndroidChannelID,
		&i.AndroidAccentColor,
		&i.AndroidLedColor,
		&i.AndroidGroup,
		&i.AndroidGroupMessage,
		&i.AndroidSound,
		&i.IosSound,
		&i.WpWnsSound,
		&i.AdmSound,
		&i.ChromeWebImage,
		&i.ChromeWebIcon,
		&i.ChromeWebBadge,
		&i.ChromeWebColor,
		&i.ChromeWebSound,
		&i.Url,
		&i.WebUrl,
		&i.AppUrl,
		&i.Data,
		&i.Filters,
		&i.Tags,
		&i.SendAfter,
		&i.DelayedOption,
		&i.DeliveryTimeOfDay,
		&i.Ttl,
		&i.Priority,
		&i.OnesignalNotificationID,
		&i.OnesignalStatus,
		&i.OnesignalResponse,
		&i.OnesignalError,
		&i.TargetUserID,
		&i.SourceServiceID,
		&i.SourceUserID,
		&i.NotificationType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getNotificationStats = `-- name: GetNotificationStats :one
SELECT 
    COUNT(*) as total_notifications,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_notifications,
    COUNT(*) FILTER (WHERE status = 'sent') as sent_notifications,
    COUNT(*) FILTER (WHERE status = 'delivered') as delivered_notifications,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_notifications,
    COUNT(*) FILTER (WHERE read_at IS NOT NULL) as read_notifications,
    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '24 hours') as notifications_last_24h
FROM notifications
WHERE target_user_id = $1
`

type GetNotificationStatsRow struct {
	TotalNotifications     int64 `json:"total_notifications"`
	PendingNotifications   int64 `json:"pending_notifications"`
	SentNotifications      int64 `json:"sent_notifications"`
	DeliveredNotifications int64 `json:"delivered_notifications"`
	FailedNotifications    int64 `json:"failed_notifications"`
	ReadNotifications      int64 `json:"read_notifications"`
	NotificationsLast24h   int64 `json:"notifications_last_24h"`
}

func (q *Queries) GetNotificationStats(ctx context.Context, targetUserID pgtype.UUID) (GetNotificationStatsRow, error) {
	row := q.db.QueryRow(ctx, getNotificationStats, targetUserID)
	var i GetNotificationStatsRow
	err := row.Scan(
		&i.TotalNotifications,
		&i.PendingNotifications,
		&i.SentNotifications,
		&i.DeliveredNotifications,
		&i.FailedNotifications,
		&i.ReadNotifications,
		&i.NotificationsLast24h,
	)
	return i, err
}

const getNotificationStatsByType = `-- name: GetNotificationStatsByType :one
SELECT 
    COUNT(*) as total_notifications,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_notifications,
    COUNT(*) FILTER (WHERE status = 'sent') as sent_notifications,
    COUNT(*) FILTER (WHERE status = 'delivered') as delivered_notifications,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_notifications
FROM notifications
WHERE notification_type = $1
`

type GetNotificationStatsByTypeRow struct {
	TotalNotifications     int64 `json:"total_notifications"`
	PendingNotifications   int64 `json:"pending_notifications"`
	SentNotifications      int64 `json:"sent_notifications"`
	DeliveredNotifications int64 `json:"delivered_notifications"`
	FailedNotifications    int64 `json:"failed_notifications"`
}

func (q *Queries) GetNotificationStatsByType(ctx context.Context, notificationType *string) (GetNotificationStatsByTypeRow, error) {
	row := q.db.QueryRow(ctx, getNotificationStatsByType, notificationType)
	var i GetNotificationStatsByTypeRow
	err := row.Scan(
		&i.TotalNotifications,
		&i.PendingNotifications,
		&i.SentNotifications,
		&i.DeliveredNotifications,
		&i.FailedNotifications,
	)
	return i, err
}

const getNotificationsByExternalUserID = `-- name: GetNotificationsByExternalUserID :many
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE $1 = ANY(include_external_user_ids)
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsByExternalUserIDParams struct {
	IncludeExternalUserIds []string `json:"include_external_user_ids"`
	Limit                  int32    `json:"limit"`
	Offset                 int32    `json:"offset"`
}

func (q *Queries) GetNotificationsByExternalUserID(ctx context.Context, arg GetNotificationsByExternalUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByExternalUserID, arg.IncludeExternalUserIds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.IncludedSegments,
			&i.ExcludedSegments,
			&i.IncludePlayerIds,
			&i.IncludeExternalUserIds,
			&i.IncludeEmailTokens,
			&i.IncludePhoneNumbers,
			&i.IncludeIosTokens,
			&i.IncludeWpWnsUris,
			&i.IncludeAmazonRegIds,
			&i.IncludeChromeRegIds,
			&i.IncludeChromeWebRegIds,
			&i.IncludeAndroidRegIds,
			&i.Contents,
			&i.Headings,
			&i.Subtitle,
			&i.Buttons,
			&i.WebButtons,
			&i.BigPicture,
			&i.LargeIcon,
			&i.SmallIcon,
			&i.IosAttachments,
			&i.AndroidChannelID,
			&i.AndroidAccentColor,
			&i.AndroidLedColor,
			&i.AndroidGroup,
			&i.AndroidGroupMessage,
			&i.AndroidSound,
			&i.IosSound,
			&i.WpWnsSound,
			&i.AdmSound,
			&i.ChromeWebImage,
			&i.ChromeWebIcon,
			&i.ChromeWebBadge,
			&i.ChromeWebColor,
			&i.ChromeWebSound,
			&i.Url,
			&i.WebUrl,
			&i.AppUrl,
			&i.Data,
			&i.Filters,
			&i.Tags,
			&i.SendAfter,
			&i.DelayedOption,
			&i.DeliveryTimeOfDay,
			&i.Ttl,
			&i.Priority,
			&i.OnesignalNotificationID,
			&i.OnesignalStatus,
			&i.OnesignalResponse,
			&i.OnesignalError,
			&i.TargetUserID,
			&i.SourceServiceID,
			&i.SourceUserID,
			&i.NotificationType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByStatus = `-- name: GetNotificationsByStatus :many
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsByStatusParams struct {
	Status *string `json:"status"`
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
}

func (q *Queries) GetNotificationsByStatus(ctx context.Context, arg GetNotificationsByStatusParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.IncludedSegments,
			&i.ExcludedSegments,
			&i.IncludePlayerIds,
			&i.IncludeExternalUserIds,
			&i.IncludeEmailTokens,
			&i.IncludePhoneNumbers,
			&i.IncludeIosTokens,
			&i.IncludeWpWnsUris,
			&i.IncludeAmazonRegIds,
			&i.IncludeChromeRegIds,
			&i.IncludeChromeWebRegIds,
			&i.IncludeAndroidRegIds,
			&i.Contents,
			&i.Headings,
			&i.Subtitle,
			&i.Buttons,
			&i.WebButtons,
			&i.BigPicture,
			&i.LargeIcon,
			&i.SmallIcon,
			&i.IosAttachments,
			&i.AndroidChannelID,
			&i.AndroidAccentColor,
			&i.AndroidLedColor,
			&i.AndroidGroup,
			&i.AndroidGroupMessage,
			&i.AndroidSound,
			&i.IosSound,
			&i.WpWnsSound,
			&i.AdmSound,
			&i.ChromeWebImage,
			&i.ChromeWebIcon,
			&i.ChromeWebBadge,
			&i.ChromeWebColor,
			&i.ChromeWebSound,
			&i.Url,
			&i.WebUrl,
			&i.AppUrl,
			&i.Data,
			&i.Filters,
			&i.Tags,
			&i.SendAfter,
			&i.DelayedOption,
			&i.DeliveryTimeOfDay,
			&i.Ttl,
			&i.Priority,
			&i.OnesignalNotificationID,
			&i.OnesignalStatus,
			&i.OnesignalResponse,
			&i.OnesignalError,
			&i.TargetUserID,
			&i.SourceServiceID,
			&i.SourceUserID,
			&i.NotificationType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByTargetUser = `-- name: GetNotificationsByTargetUser :many
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE target_user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsByTargetUserParams struct {
	TargetUserID pgtype.UUID `json:"target_user_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) GetNotificationsByTargetUser(ctx context.Context, arg GetNotificationsByTargetUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByTargetUser, arg.TargetUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.IncludedSegments,
			&i.ExcludedSegments,
			&i.IncludePlayerIds,
			&i.IncludeExternalUserIds,
			&i.IncludeEmailTokens,
			&i.IncludePhoneNumbers,
			&i.IncludeIosTokens,
			&i.IncludeWpWnsUris,
			&i.IncludeAmazonRegIds,
			&i.IncludeChromeRegIds,
			&i.IncludeChromeWebRegIds,
			&i.IncludeAndroidRegIds,
			&i.Contents,
			&i.Headings,
			&i.Subtitle,
			&i.Buttons,
			&i.WebButtons,
			&i.BigPicture,
			&i.LargeIcon,
			&i.SmallIcon,
			&i.IosAttachments,
			&i.AndroidChannelID,
			&i.AndroidAccentColor,
			&i.AndroidLedColor,
			&i.AndroidGroup,
			&i.AndroidGroupMessage,
			&i.AndroidSound,
			&i.IosSound,
			&i.WpWnsSound,
			&i.AdmSound,
			&i.ChromeWebImage,
			&i.ChromeWebIcon,
			&i.ChromeWebBadge,
			&i.ChromeWebColor,
			&i.ChromeWebSound,
			&i.Url,
			&i.WebUrl,
			&i.AppUrl,
			&i.Data,
			&i.Filters,
			&i.Tags,
			&i.SendAfter,
			&i.DelayedOption,
			&i.DeliveryTimeOfDay,
			&i.Ttl,
			&i.Priority,
			&i.OnesignalNotificationID,
			&i.OnesignalStatus,
			&i.OnesignalResponse,
			&i.OnesignalError,
			&i.TargetUserID,
			&i.SourceServiceID,
			&i.SourceUserID,
			&i.NotificationType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationsByType = `-- name: GetNotificationsByType :many
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE notification_type = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type GetNotificationsByTypeParams struct {
	NotificationType *string `json:"notification_type"`
	Limit            int32   `json:"limit"`
	Offset           int32   `json:"offset"`
}

func (q *Queries) GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotificationsByType, arg.NotificationType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.IncludedSegments,
			&i.ExcludedSegments,
			&i.IncludePlayerIds,
			&i.IncludeExternalUserIds,
			&i.IncludeEmailTokens,
			&i.IncludePhoneNumbers,
			&i.IncludeIosTokens,
			&i.IncludeWpWnsUris,
			&i.IncludeAmazonRegIds,
			&i.IncludeChromeRegIds,
			&i.IncludeChromeWebRegIds,
			&i.IncludeAndroidRegIds,
			&i.Contents,
			&i.Headings,
			&i.Subtitle,
			&i.Buttons,
			&i.WebButtons,
			&i.BigPicture,
			&i.LargeIcon,
			&i.SmallIcon,
			&i.IosAttachments,
			&i.AndroidChannelID,
			&i.AndroidAccentColor,
			&i.AndroidLedColor,
			&i.AndroidGroup,
			&i.AndroidGroupMessage,
			&i.AndroidSound,
			&i.IosSound,
			&i.WpWnsSound,
			&i.AdmSound,
			&i.ChromeWebImage,
			&i.ChromeWebIcon,
			&i.ChromeWebBadge,
			&i.ChromeWebColor,
			&i.ChromeWebSound,
			&i.Url,
			&i.WebUrl,
			&i.AppUrl,
			&i.Data,
			&i.Filters,
			&i.Tags,
			&i.SendAfter,
			&i.DelayedOption,
			&i.DeliveryTimeOfDay,
			&i.Ttl,
			&i.Priority,
			&i.OnesignalNotificationID,
			&i.OnesignalStatus,
			&i.OnesignalResponse,
			&i.OnesignalError,
			&i.TargetUserID,
			&i.SourceServiceID,
			&i.SourceUserID,
			&i.NotificationType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT id, app_id, included_segments, excluded_segments, include_player_ids, include_external_user_ids, include_email_tokens, include_phone_numbers, include_ios_tokens, include_wp_wns_uris, include_amazon_reg_ids, include_chrome_reg_ids, include_chrome_web_reg_ids, include_android_reg_ids, contents, headings, subtitle, buttons, web_buttons, big_picture, large_icon, small_icon, ios_attachments, android_channel_id, android_accent_color, android_led_color, android_group, android_group_message, android_sound, ios_sound, wp_wns_sound, adm_sound, chrome_web_image, chrome_web_icon, chrome_web_badge, chrome_web_color, chrome_web_sound, url, web_url, app_url, data, filters, tags, send_after, delayed_option, delivery_time_of_day, ttl, priority, onesignal_notification_id, onesignal_status, onesignal_response, onesignal_error, target_user_id, source_service_id, source_user_id, notification_type, status, created_at, updated_at, sent_at, delivered_at FROM notifications 
WHERE status = 'pending'
  AND (send_after IS NULL OR send_after <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingNotifications(ctx context.Context, limit int32) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.IncludedSegments,
			&i.ExcludedSegments,
			&i.IncludePlayerIds,
			&i.IncludeExternalUserIds,
			&i.IncludeEmailTokens,
			&i.IncludePhoneNumbers,
			&i.IncludeIosTokens,
			&i.IncludeWpWnsUris,
			&i.IncludeAmazonRegIds,
			&i.IncludeChromeRegIds,
			&i.IncludeChromeWebRegIds,
			&i.IncludeAndroidRegIds,
			&i.Contents,
			&i.Headings,
			&i.Subtitle,
			&i.Buttons,
			&i.WebButtons,
			&i.BigPicture,
			&i.LargeIcon,
			&i.SmallIcon,
			&i.IosAttachments,
			&i.AndroidChannelID,
			&i.AndroidAccentColor,
			&i.AndroidLedColor,
			&i.AndroidGroup,
			&i.AndroidGroupMessage,
			&i.AndroidSound,
			&i.IosSound,
			&i.WpWnsSound,
			&i.AdmSound,
			&i.ChromeWebImage,
			&i.ChromeWebIcon,
			&i.ChromeWebBadge,
			&i.ChromeWebColor,
			&i.ChromeWebSound,
			&i.Url,
			&i.WebUrl,
			&i.AppUrl,
			&i.Data,
			&i.Filters,
			&i.Tags,
			&i.SendAfter,
			&i.DelayedOption,
			&i.DeliveryTimeOfDay,
			&i.Ttl,
			&i.Priority,
			&i.OnesignalNotificationID,
			&i.OnesignalStatus,
			&i.OnesignalResponse,
			&i.OnesignalError,
			&i.TargetUserID,
			&i.SourceServiceID,
			&i.SourceUserID,
			&i.NotificationType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET
    read_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, id)
	return err
}

const updateNotificationOneSignalData = `-- name: UpdateNotificationOneSignalData :exec
UPDATE notifications
SET
    onesignal_notification_id = $2,
    onesignal_status = $3,
    onesignal_response = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationOneSignalDataParams struct {
	ID                      uuid.UUID       `json:"id"`
	OnesignalNotificationID *string         `json:"onesignal_notification_id"`
	OnesignalStatus         *string         `json:"onesignal_status"`
	OnesignalResponse       json.RawMessage `json:"onesignal_response"`
}

func (q *Queries) UpdateNotificationOneSignalData(ctx context.Context, arg UpdateNotificationOneSignalDataParams) error {
	_, err := q.db.Exec(ctx, updateNotificationOneSignalData,
		arg.ID,
		arg.OnesignalNotificationID,
		arg.OnesignalStatus,
		arg.OnesignalResponse,
	)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications
SET
    status = $2,
    onesignal_notification_id = COALESCE($3, onesignal_notification_id),
    onesignal_status = COALESCE($4, onesignal_status),
    onesignal_response = COALESCE($5, onesignal_response),
    onesignal_error = COALESCE($6, onesignal_error),
    sent_at = CASE WHEN $2 = 'sent' THEN NOW() ELSE sent_at END,
    delivered_at = CASE WHEN $2 = 'delivered' THEN NOW() ELSE delivered_at END,
    failed_at = CASE WHEN $2 = 'failed' THEN NOW() ELSE failed_at END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID                      uuid.UUID       `json:"id"`
	Status                  *string         `json:"status"`
	OnesignalNotificationID *string         `json:"onesignal_notification_id"`
	OnesignalStatus         *string         `json:"onesignal_status"`
	OnesignalResponse       json.RawMessage `json:"onesignal_response"`
	OnesignalError          *string         `json:"onesignal_error"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus,
		arg.ID,
		arg.Status,
		arg.OnesignalNotificationID,
		arg.OnesignalStatus,
		arg.OnesignalResponse,
		arg.OnesignalError,
	)
	return err
}
