// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupOldNotifications(ctx context.Context) error
	// Records an email dispatch to the email sending service for compliance
	// purposes
	CreateEmailDispatch(ctx context.Context, arg CreateEmailDispatchParams) (EmailDispatch, error)
	// Persists an email request to the database for replayability
	CreateEmailRequest(ctx context.Context, arg CreateEmailRequestParams) (EmailRequest, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetEmailRequestByID(ctx context.Context, id uuid.UUID) (EmailRequest, error)
	// Orders the time it was recieved ie the most previous
	GetEmailRequestByService(ctx context.Context, serviceID string) ([]EmailRequest, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationByOneSignalID(ctx context.Context, onesignalNotificationID *string) (Notification, error)
	GetNotificationStats(ctx context.Context, targetUserID pgtype.UUID) (GetNotificationStatsRow, error)
	GetNotificationStatsByType(ctx context.Context, notificationType *string) (GetNotificationStatsByTypeRow, error)
	GetNotificationsByExternalUserID(ctx context.Context, arg GetNotificationsByExternalUserIDParams) ([]Notification, error)
	GetNotificationsByStatus(ctx context.Context, arg GetNotificationsByStatusParams) ([]Notification, error)
	GetNotificationsByTargetUser(ctx context.Context, arg GetNotificationsByTargetUserParams) ([]Notification, error)
	GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error)
	GetPendingNotifications(ctx context.Context, limit int32) ([]Notification, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	MarkNotificationAsRead(ctx context.Context, id uuid.UUID) error
	// Updates an email_request record effectively setting its status to one of
	// the predefined statuses
	UpdateEmailRequestStatusByID(ctx context.Context, arg UpdateEmailRequestStatusByIDParams) (EmailRequest, error)
	UpdateNotificationOneSignalData(ctx context.Context, arg UpdateNotificationOneSignalDataParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
