// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupOldNotifications(ctx context.Context) error
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	CreateEmailRecipient(ctx context.Context, arg CreateEmailRecipientParams) (EmailRecipient, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetEmailByExternalID(ctx context.Context, externalID pgtype.UUID) (Email, error)
	GetEmailByID(ctx context.Context, id uuid.UUID) (Email, error)
	GetEmailRecipients(ctx context.Context, arg GetEmailRecipientsParams) ([]EmailRecipient, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationByOneSignalID(ctx context.Context, onesignalNotificationID *string) (Notification, error)
	GetNotificationStats(ctx context.Context, targetUserID pgtype.UUID) (GetNotificationStatsRow, error)
	GetNotificationStatsByType(ctx context.Context, notificationType *string) (GetNotificationStatsByTypeRow, error)
	GetNotificationsByExternalUserID(ctx context.Context, arg GetNotificationsByExternalUserIDParams) ([]Notification, error)
	GetNotificationsByStatus(ctx context.Context, arg GetNotificationsByStatusParams) ([]Notification, error)
	GetNotificationsByTargetUser(ctx context.Context, arg GetNotificationsByTargetUserParams) ([]Notification, error)
	GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error)
	GetPendingNotifications(ctx context.Context, limit int32) ([]Notification, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	MarkNotificationAsRead(ctx context.Context, id uuid.UUID) error
	UpdateNotificationOneSignalData(ctx context.Context, arg UpdateNotificationOneSignalDataParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
