// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupOldNotifications(ctx context.Context) error
	// Records an email dispatch to the email sending service for compliance
	// purposes
	CreateEmailDispatch(ctx context.Context, arg CreateEmailDispatchParams) (EmailDispatch, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNotification(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetEmailRequestByID(ctx context.Context, id uuid.UUID) (EmailRequest, error)
	// Used to detect a duplicate send before calling Resend: if a request with
	// this queue_message_id was already dispatched, the caller must skip
	// resending rather than upsert-and-retry, or a legitimate DLX redelivery
	// and an external duplicate republish become indistinguishable and both
	// would trigger a second real send.
	GetEmailRequestByQueueMessageID(ctx context.Context, queueMessageID string) (EmailRequest, error)
	// Orders the time it was recieved ie the most previous
	GetEmailRequestByService(ctx context.Context, arg GetEmailRequestByServiceParams) ([]EmailRequest, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationByOneSignalID(ctx context.Context, onesignalNotificationID *string) (Notification, error)
	// Used to detect a duplicate send before calling OneSignal: if a
	// notification with this queue_message_id was already sent, the caller
	// must skip resending rather than upsert-and-retry, or a legitimate DLX
	// redelivery and an external duplicate republish become indistinguishable
	// and both would trigger a second real send.
	GetNotificationByQueueMessageID(ctx context.Context, queueMessageID *string) (Notification, error)
	GetNotificationStats(ctx context.Context, targetUserID pgtype.UUID) (GetNotificationStatsRow, error)
	GetNotificationStatsByType(ctx context.Context, notificationType *string) (GetNotificationStatsByTypeRow, error)
	GetNotificationsByExternalUserID(ctx context.Context, arg GetNotificationsByExternalUserIDParams) ([]Notification, error)
	GetNotificationsByStatus(ctx context.Context, arg GetNotificationsByStatusParams) ([]Notification, error)
	GetNotificationsByTargetUser(ctx context.Context, arg GetNotificationsByTargetUserParams) ([]Notification, error)
	GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]Notification, error)
	GetPendingNotifications(ctx context.Context, limit int32) ([]Notification, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username *string) (User, error)
	MarkNotificationAsRead(ctx context.Context, id uuid.UUID) error
	// Updates an email_request record effectively setting its status to one of
	// the predefined statuses
	UpdateEmailRequestStatusByID(ctx context.Context, arg UpdateEmailRequestStatusByIDParams) (EmailRequest, error)
	UpdateNotificationOneSignalData(ctx context.Context, arg UpdateNotificationOneSignalDataParams) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error)
	// Persists an email request to the database for replayability, or updates
	// it in place if this is a retry of the same queue_message_id (dead-lettered
	// redelivery) — retrying must not hit the queue_message_id UNIQUE
	// constraint as a fresh insert, or the retry mechanism would just fail
	// forever on the second attempt without ever reaching Resend again.
	UpsertEmailRequest(ctx context.Context, arg UpsertEmailRequestParams) (EmailRequest, error)
	// Inserts a notification send attempt, or updates it in place if this is a
	// retry of the same queue_message_id (dead-lettered redelivery). Keeping one
	// row per logical send, updated across attempts, matches how this table
	// already behaves (a single mutable outcome row, not an attempt-history
	// table like email_requests/email_dispatches).
	UpsertNotification(ctx context.Context, arg UpsertNotificationParams) (Notification, error)
	// Registers a service on first use so email onboarding is self-service;
	// ON CONFLICT DO UPDATE (a no-op) instead of DO NOTHING so RETURNING always
	// yields exactly one row, whether the service already existed or not.
	UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
