// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package repository

import (
	"context"
)

const upsertService = `-- name: UpsertService :one
INSERT INTO services (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET is_active = services.is_active
RETURNING id, name, description, is_active, created_at
`

type UpsertServiceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Registers a service on first use so email onboarding is self-service;
// ON CONFLICT DO UPDATE (a no-op) instead of DO NOTHING so RETURNING always
// yields exactly one row, whether the service already existed or not.
func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, upsertService, arg.ID, arg.Name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
